// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eszteylvawpsxgpukthr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzenRleWx2YXdwc3hncHVrdGhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDcxMzQsImV4cCI6MjA3NDI4MzEzNH0.S98oFwzxrLzUiEWoBT9Ofxm7GYU7qr7yvfsMfTNlu5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});